alph/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'alph'
urlpatterns = [
    path("", views.index, name="index"),
    path("superman", views.superman.as_view(), name="superman"),
    path("alph4", views.alph4, name="alph4"),
    path("about", views.about, name="about"),
    path("why", views.why, name="why"),
    path("contact", views.contact, name="contact"),
    path("legal", views.legal, name="legal"),
    path("faq", views.faq, name="faq"),
    path("superver/<str:pk>", views.superver.as_view(), name="superver"),
    path("superwit/<str:pk>", views.superwit.as_view(), name="superwit"),
    path("testimonal", views.testimonals, name="testimonals"),
    path("platform", views.platform, name="platform"),
    path("web", views.web, name="web"),
    path("appwit/<str:pk>", views.appwit, name="appwit"),
    path("appwit2/<str:pk>", views.appwit2, name="appwit2"),
    path("appwit3/<str:pk>", views.appwit3, name="appwit3"),
    path("appwit4/<str:pk>", views.appwit4, name="appwit4"),
    path("superdep/<str:pk>", views.superdep.as_view(), name="superdep"),
    path("appdep", views.appdep, name="appdep"),
    path("appdep2/<str:pk>", views.appdep2, name="appdep2"),
    path("metatrader", views.metatrader, name="metatrader"),
    
         ]

trading/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.static import serve

urlpatterns = [
    path('popsi', admin.site.urls),
    path('', include('alph.urls')),
    path('', include('django.contrib.auth.urls')),
    path('account', include('authz.urls')),
    path('market', include('market.urls')),
    path('dashboard', include('dashboard.urls')),
    path('user_profile', include('user_profile.urls')),
]
handler404 = 'alph.views.error_404'
handler500 = 'alph.views.error_500'

alph/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    full_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    message = models.TextField()
    language = models.CharField(max_length=50)
    existing= models.CharField(max_length=5)
    phone_num= models.CharField(max_length=20,null=True)
    account_number = models.CharField(max_length=20,null=True)
    enquiry_type = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    attended_to = models.BooleanField(default=False)

    def __str__(self):
        if len(self.message) < 15:
            return self.message
        return self.text[:11] + ' ...'

alph/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from user_profile.models import Document
from dashboard.models import Withdraw
from authz.models import User
from user_profile.models import Account
from dashboard.models import Payment
from .models import Contact

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return redirect('dashboard:dash')
    context = {}
    return render(request, "alph/index.html", context)

class superman(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        if (user.is_superuser == False):
            return render(request, "alph/404.html")
        email = user.email
        deposit = Payment.objects.filter(verified=False)
        withdraw = Withdraw.objects.filter(status=False)
        document = Document.objects.filter(status=False)
        context= {"user":user,"withdraw":withdraw,"document":document,"deposit":deposit}
        return render(request, "alph/super.html", context)
   

class superver(LoginRequiredMixin, View):
    def get(self, request, pk):
        user = request.user
        if (user.is_superuser == False):
            return render(request, "alph/404.html")
        cust= User.objects.get(email=pk)
        email = cust.email
        document = Document.objects.get(email=email)
        user = request.user
        context= {"user":user, "document":document}
        return render(request, "alph/superver.html", context)
    

class superwit(LoginRequiredMixin, View):
    def get(self, request, pk):
        user = request.user
        if user.is_superuser == False:
            return render(request, "alph/404.html")
        withdraw = Withdraw.objects.get(ref=pk)
        context= {"user":user, "withdraw":withdraw}
        return render(request, "alph/superwit.html", context)

class superdep(LoginRequiredMixin, View):
    def get(self, request, pk):
        user = request.user
        if user.is_superuser == False:
            return render(request, "alph/404.html")
        payment = Payment.objects.get(ref=pk)
        context= {"user":user, "payment":payment}
        return render(request, "alph/superdep.html", context)


def alph4(request):
    return render(request, "alph/alph4.html")

def appwit(request,pk):
    user = request.user
    if (user.is_superuser == False):
        return render(request, "alph/404.html")
    Withdraw.objects.filter(ref=pk).update(status=True)
    return redirect('alph:superman')

def appdep(request):
    if request.method == "POST":
        user = request.user
        if (user.is_superuser == False):
            return render(request, "alph/404.html")

        ref = request.POST['ref']
        payment = Payment.objects.get(ref=ref)
        amount = request.POST['amount']
        user = Account.objects.get(account_number=payment.acc)
        balance = int(user.balance) + int(amount)
        Account.objects.filter(account_number=payment.acc).update(balance=balance)
        Payment.objects.filter(ref=ref).update(verified=True)
        return redirect('alph:superman')






    user = request.user
    if (user.is_superuser == False):
        return render(request, "alph/404.html")
    payment = Payment.objects.get(ref=pk)
    amount = payment.amount
    user = Account.objects.get(account_number=payment.acc)
    balance = int(user.balance) + int(amount)
    Account.objects.filter(account_number=payment.acc).update(balance=balance)
    Payment.objects.filter(ref=pk).update(verified=True)
    return redirect('alph:superman')
    

def appdep2(request,pk):
    user = request.user
    if (user.is_superuser == False):
        return render(request, "alph/404.html")
    Payment.objects.filter(ref=pk).delete()
    return redirect('alph:superman')

def appwit2(request,pk):
    user = request.user
    if (user.is_superuser == False):
        return render(request, "alph/404.html")
    withdraw = Withdraw.objects.get(ref=pk)
    acc= withdraw.account
    user = Account.objects.get(account_number=withdraw.account)
    balance = int(user.balance) + int(withdraw.amount)
    Account.objects.filter(account_number=withdraw.account).update(balance=balance)
    Withdraw.objects.filter(ref=pk).delete()
    return redirect('alph:superman')
def appwit3(request,pk):
    user = request.user
    if (user.is_superuser == False):
        return render(request, "alph/404.html")
    User.objects.filter(email=pk).update(is_document_verified=True)
    Document.objects.filter(email=pk).update(status=True)
    return redirect('alph:superman')
def appwit4(request,pk):
    user = request.user
    if (user.is_superuser == False):
        return render(request, "alph/404.html")
    User.objects.filter(email=pk).update(is_document_submitted=False)
    Document.objects.filter(email=pk).delete()
    return redirect('alph:superman')
    
def about(request):
    return render(request, "alph/about.html")
def why(request):
    return render(request, "alph/why.html")
def contact(request):
    if request.method == "POST":
        full_name=request.POST['input_1']
        email=request.POST['input_3']
        language=request.POST['input_8']
        existing = request.POST['input_4']
        try:
            phone_num = request.POST['input_7']
        except:
            phone_num = None

        try:
            account_number = request.POST['input_6']
        except:
            account_number = None
        enquiry_type = request.POST['input_7']
        message=request.POST['message']
        contact = Contact(
            full_name=full_name, email=email,language=language,existing=existing,phone_num=phone_num,account_number=account_number,enquiry_type=enquiry_type, message=message)
        contact.save()
    return render(request, "alph/contact.html")
def legal(request):
    return render(request, "alph/legal.html")
def faq(request):
    return render(request, "alph/faq.html")
def testimonals(request):
    return render(request, "alph/testimonal.html")

def platform(request):
    return render(request, "alph/platform.html")
def web(request):
    return render(request, "alph/web.html")
def metatrader(request):
    return render(request, "alph/metatrader.html")
def metatrader(request):
    return render(request, "alph/metatrader.html")

def error_404(request,exception):
    return render(request, "alph/404.html")

def error_500(request):
    return render(request, "alph/500.html")

alph/templates/alph/super.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'lte/css/superboard.css' %}">
    <title>Super Admin Board</title>
</head>

<header>
    <p><h2>ADMIN DASHBOARD</h2></p>
</header>
            <br>
<body>

    {% if user.is_superuser %}
    
    <p><h4>You are viewing this because you are a superuser</h4></p> 
    
    <main>
        <h3>Pending Deposits</h3>
    {% if deposit %}
    </main>

    <ul>
        {% for i in deposit %}
    <li>
    <a href="{% url 'alph:superdep' i.ref %}">{{ i.ref }}</a> 
    </li>
        {% endfor %}

    </ul>

    {% else %}
    <p>No pending Deposit requests</p>

    {% endif %}


    <h3>Pending Withdrawals</h3>
    {% if withdraw %}
    </main>

    <ul>
        {% for i in withdraw %}
    <li>
    <a href="{% url 'alph:superwit' i.ref %}">{{ i.ref }}</a> 
    </li>
        {% endfor %}

    </ul>

    {% else %}
    <p>No pending Withdrawal requests</p>

    {% endif %}

    <h3>Pending Verifications</h3>

    {% if document %}
    <ul>
        {% for i in document %}
    <li>
        <a href="{% url 'alph:superver' i.email %}">{{ i.email }}</a> 
    </li>
    {% endfor %}


    </ul>


    {% else %}
    <p>No pending Document Verification</p>

    {% endif %}

            <br><br>

    {% else %}
    You dont have access to view this page

    {% endif %}

</body>
</html>

alph/templates/alph/superdep.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'lte/css/superboard.css' %}">
    			<link rel="stylesheet" href="{% static 'lte/css/icomoon.css' %}" />
		<link rel="stylesheet" href="{% static 'lte/css/style-providers-list.css' %}" />
	<link rel="stylesheet" href="{% static 'lte/css/common.css' %}" />
    <title>Superdep</title>

    <style>
    .popup {
	width: 400px;
	background: #fff;
	border-radius: 6px;
	position: absolute;
	top: 10;
	left: 50%;
	transform: translate(-50%, -50%) scale(0.001);
	text-align: center;
	padding: 0 30px 30px;
	color: #333;
	visibility: hidden;
	transition: transform 0.4s, top 0.4s;
}
.open-popup {
	visibility: visible;
	top: 80%;
	transform: translate(-50%, -50%) scale(1);
}

.inp {
	width: 20%;
}

.popup img {
	width: 100px;
	margin-top: -50px;
	border-radius: 50%;
	box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
}
/* .popup h4{
    font-size: 38px;
    font-weight: 500;
    margin: 30px 0 10px;

} */
/* @media screen and (max-width: 1000px) {
	.open-popup {
		width: 40%;
		margin-left: 30%;
		margin-right: 30%;
		
	}
} */

.popup2 {
	width: 400px;
	background: #fff;
	border-radius: 6px;
	position: absolute;
	top: 10;
	left: 50%;
	transform: translate(-50%, -50%) scale(0.001);
	text-align: center;
	padding: 0 30px 30px;
	color: #333;
	visibility: hidden;
	transition: transform 0.4s, top 0.4s;
}
.open-popup2 {
	visibility: visible;
	top: 80%;
	transform: translate(-50%, -50%) scale(1);
}

.inp {
	width: 20%;
}

.popup2 img {
	width: 100px;
	margin-top: -50px;
	border-radius: 50%;
	box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
}
</style>
</head>

<header>
    <p><h2>ADMIN DASHBOARD</h2></p>
</header>
            <br>
<body style="color: yellow;">
        {% if user.is_superuser %}

    <p>You are viewing this because you are a superuser </p> 

    <ul>
        <li> Reference No : {{ payment.ref }}</li>
        <li> Date : {{ payment.date_created }}</li>
        <li> Account Id : {{ payment.acc }}</li>
        <li> Amount : {{ payment.amount }}</li>
        <li> Currency : {{ payment.currency }}</li>
        <li> Preferred Payment Bank: {{ payment.preferred_bank }}</li>
        <li> Deposit Bank Name : {{ payment.bank_name }}</li>
       
        
        
    </ul>

    <div style="text-align: center; justify-content: center; color: yellow;">
<form action="{% url 'alph:appdep'%}" method="post">
    {% csrf_token %}
<p>(please confirm the amount and currency before submiting)</p>
<label for="amount">Enter Amount to approve:</label><br>
<input type="number" name="amount" style="background-color:#fff;" required><br>
<!-- <input type="submit" value="Approve" style="background-color: #fff; color:black"><br> -->
<input type="hidden" value="{{ payment.ref }}" name="ref">

<div class="card-footer">

                    <div class="form-group">
                       

								<div class="popup" id="popup">
									<img src="{% static 'lte/images/m8.png' %}">
									<span style="background-color: white;" onclick="closePopup()" class="icon-cross"></span>
									<h4 style="background-color: white; color: red;">Please make sure youve checked the actual amount deposited</h4>
									<button 
                                class="btn btn-default btn-blue"
                                type="submit" onclick="closePopup()">Proceed</button>
								</div>
                    </div>

            </div>
			<input style="background-color: #fff; color:black;"  type="button" value="Approve" class="inp btn btn-default btn-blue"  onclick="openPopup()">
           </div>


</form>
</div>
 <div style="text-align: center;">
    <p>Once you click on Delete transaction, the transaction reference will be deleted from the database and it cannot be reversed!!!
    </p>
           <a href="{% url 'alph:appdep2' payment.ref %}"><input style="background-color: #fff; color:black;"  type="button" value="Delete transaction" class="inp btn btn-default btn-blue" onclick="Delete()"></a>
        </div>

    {% else %}
    <p>You re not allowed to view this page</p>
    {% endif %}


    <script>
	let popup= document.getElementById("popup");

	function openPopup(){
		popup.classList.add("open-popup")
	}
	function closePopup(){
		popup.classList.remove("open-popup")
	}
</script>

</body>
</html>

alph/templates/alph/superver.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'lte/css/superboard.css' %}">
    <title>Superuser Board</title>
</head>

<header>
    <p><h2>ADMIN DASHBOARD</h2></p>
</header>
            <br>
<body>
       {% if user.is_superuser %}

       <p>You are viewing this because you are a superuser </p> 
       <ul>
              <li> First name : {{ document.first_name }}</li>
              <li> Last name : {{ document.last_name }}</li>
              <li> E-mail: {{ document.email }}</li>
              <li> Nationality : {{ document.nationality }}</li>
              <li> Gender : {{ document.gender }}</li>
              <li> Date of birth : {{ document.dob_dd }}</li>
              <li> TIN : {{ document.tin }}</li>
              <li> Country of Tax Residence: {{ document.tax_country }}</li>
              <li> Address Line 1: {{ document.address1 }}</li>
              <li> Address Line 2: {{ document.address2 }}</li>
              <li> Town/City: {{ document.town }}</li>
              <li> Post Code : {{ document.postcode }}</li>
              <li> Country of residence: {{ document.country }}</li>
              <li> Landline: {{ document.phone_landline }}</li>
              <li> Mobile: {{ document.phone_mobile }}</li>
              <li> Employment status : {{ document.employment_status }}</li>
              <li> Business Nature : {{ document.business_nature }}</li>
              <li> Source of Funds:{{ document.funds_source }}</li>
              <li> Expected Deposit : {{ document.expected_deposit_id }}</li>
              <li> Annual Income : {{ document.annual_income }}</li>
              <li> Net worth : {{ document.annual_income }}</li>
              <li> Traded Forex : {{ document.traded_forex }}</li>
              <li> Traded Forex Frequency : {{ document.traded_forex_frequency }}</li>
              <li> Traded Forex volumn : {{ document.traded_forex_volume }}</li>
              <li> Traded Bond Frequency : {{ document.traded_bonds_frequency }}</li>
              <li> Traded Bond volume : {{ document.traded_bonds_volume }}</li>
              <li> Traded product frequency : {{ document.traded_products_frequency }}</li>
              <li> Traded product Volume : {{ document.traded_products_volume }}</li>
              <li> Seminar Experience : {{ document.seminar_experience }}</li>
              <li> Seminar Course Experience : {{ document.seminar_course_experience }}</li>
              <li> Work Experience : {{ document.work_experience }}</li>
              <li> Work Qualification experience : {{ document.work_qualification_experience }}</li>
       </ul>
       <li><a href="{% url 'alph:appwit3' document.email %}">Approve</a></li>
       <li><a href="{% url 'alph:appwit4' document.email %}">Cancel</a></li>
       {% else %}
       <p>You are not allowed to view this page</p>
       {% endif %}
       
</body>
</html>

alph/templates/alph/superwit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'lte/css/superboard.css' %}">
    <title>Superwit</title>
</head>

<header>
    <p><h2>ADMIN DASHBOARD</h2></p>
</header>
            <br>
<body>
        {% if user.is_superuser %}

    <p>You are viewing this because you are a superuser </p> 

    <ul>
        <li> Reference No : {{ withdraw.ref }}</li>
        <li> Date : {{ withdraw.date }}</li>
        <li> Account Id : {{ withdraw.account }}</li>
        <li> Amount : {{ withdraw.amount }}</li>
        <li> Full name : {{ withdraw.beneficiary_fullname }}</li>
        <li> Address : {{ withdraw.beneficiary_address }}</li>
        <li> City : {{ withdraw.beneficiary_city }}</li>
        <li> Zip : {{ withdraw.beneficiary_zip }}</li>
        <li> Country : {{ withdraw.beneficiary_country }}</li>
        <li> Bank account : {{ withdraw.bank_account }}</li>
        <li> Bank name : {{ withdraw.bank_name }}</li>
        <li> Branch Code : {{ withdraw.branch_code }}</li>
        <li> Branch address : {{ withdraw.bank_address }}</li>
        <li> Swift : {{ withdraw.beneficiary_swift }}</li>
        <li> Bic : {{ withdraw.bic }}</li>
        <li> Notes : {{ withdraw.notes }}</li>
        
        
    </ul>

    <li><a href="{% url 'alph:appwit' withdraw.ref %}">Approve</a></li>
    <li><a href="{% url 'alph:appwit2' withdraw.ref %}">Cancel</a></li>

    {% else %}
    <p>You re not allowed to view this page</p>
    {% endif %}
</body>
</html>