alph/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'alph'
urlpatterns = [
    path("", views.index, name="index"),
    path("superman", views.superman.as_view(), name="superman"),
    path("alph4", views.alph4, name="alph4"),
    path("about", views.about, name="about"),
    path("why", views.why, name="why"),
    path("contact", views.contact, name="contact"),
    path("legal", views.legal, name="legal"),
    path("faq", views.faq, name="faq"),
    path("superver/<str:pk>", views.superver.as_view(), name="superver"),
    path("superwit/<str:pk>", views.superwit.as_view(), name="superwit"),
    path("testimonal", views.testimonals, name="testimonals"),
    path("platform", views.platform, name="platform"),
    path("web", views.web, name="web"),
    path("appwit/<str:pk>", views.appwit, name="appwit"),
    path("appwit2/<str:pk>", views.appwit2, name="appwit2"),
    path("appwit3/<str:pk>", views.appwit3, name="appwit3"),
    path("appwit4/<str:pk>", views.appwit4, name="appwit4"),
    path("superdep/<str:pk>", views.superdep.as_view(), name="superdep"),
    path("appdep", views.appdep, name="appdep"),
    path("appdep2/<str:pk>", views.appdep2, name="appdep2"),
    path("metatrader", views.metatrader, name="metatrader"),
    
         ]

authz/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'authz'
urlpatterns = [
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("signup", views.signup, name="signup"),
    path("resend_email", views.resend_email, name="resend_email"),
    path('activate_user/<uidb64>/<token>', views.activate_user, name='activate'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
   
]

trading/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.static import serve

urlpatterns = [
    path('popsi', admin.site.urls),
    path('', include('alph.urls')),
    path('', include('django.contrib.auth.urls')),
    path('account', include('authz.urls')),
    path('market', include('market.urls')),
    path('dashboard', include('dashboard.urls')),
    path('user_profile', include('user_profile.urls')),
]
handler404 = 'alph.views.error_404'
handler500 = 'alph.views.error_500'

authz/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

class CustomUserManager(BaseUserManager):
    def _create_user(self,email,password, first_name, last_name, phone_num, date_of_birth,country, **extra_fields):
        if not email:
            raise valueerror("Email must be provided")
        if not password:
            raise valueerror("Password must be provided")

        user = self.model(
            email  = self.normalize_email(email),
            first_name = first_name,
            last_name = last_name,
            phone_num = phone_num,
            date_of_birth = date_of_birth,
            country = country,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, first_name, last_name,phone_num, date_of_birth,country, **extra_fields):
        extra_fields.setdefault('is_staff',False)
        extra_fields.setdefault('is_active',True)
        extra_fields.setdefault('is_superuser',False)
        extra_fields.setdefault('is_email_verified',False)
        extra_fields.setdefault('is_document_submitted',False)
        extra_fields.setdefault('is_document_verified',False)
        return self._create_user(email, password,first_name, last_name, phone_num, date_of_birth, country)

    def create_superuser(self, email, password,**extra_fields):
        extra_fields.setdefault('is_staff',True)
        extra_fields.setdefault('is_active',True)
        extra_fields.setdefault('is_superuser',True)
        extra_fields.setdefault('is_email_verified',True)
        extra_fields.setdefault('is_document_submitted',True)
        extra_fields.setdefault('is_document_verified',True)
        return self._create_user(email, password,first_name=None, last_name=None, phone_num=None, date_of_birth=None, country=None, **extra_fields)


class User(AbstractBaseUser,PermissionsMixin):
    email= models.EmailField(unique=True, max_length=254)
    first_name = models.CharField(max_length=240, null=True)
    last_name = models.CharField(max_length=240, null=True)
    phone_num = models.CharField(max_length=50, null=True)
    date_of_birth = models.CharField(max_length=50, null=True)
    country = models.CharField(max_length=50, null=True)
    is_staff = models.BooleanField(default=False)
    is_active =  models.BooleanField(default=True)
    is_superuser =  models.BooleanField(default=False)
    is_document_submitted = models.BooleanField(default=False)
    is_document_verified = models.BooleanField(default=False)
    is_email_verified = models.BooleanField(default=False)
    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELD = ['email']

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

authz/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import  auth
from .models import User
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.urls import reverse_lazy, reverse
import os
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str, force_str,DjangoUnicodeDecodeError
from .utils import generate_token
from django.core.mail import EmailMessage
from django.conf import settings
import random
from user_profile.models import Account
def generateReferenceNumber():
    return random.randrange(1000000000, 9999999999)

def generateAccountNumber():
    return random.randrange(111111, 999999)

# Create your views here.


def send_activation_email(user,request):
    current_site = get_current_site(request)
    email_subject = 'Activate your account'
    email_body = render_to_string('authz/activate.html', {
        'user':user,
        'domain': current_site,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': generate_token.make_token(user)
    })

    email= EmailMessage(subject=email_subject,body=email_body, from_email= settings.EMAIL_FROM_USER,to=[user.email])
    email.send()

def login(request):
    if request.method == 'POST':
        email= request.POST['email']
        password = request.POST['password']
        if User.objects.filter(email=email).exists():
            user = auth.authenticate(email=email,password=password)
                

            if user is not None:
                if not user.is_email_verified:
                    messages.info(request, 'Email not  verified yet, do that before you can log in')
                    return redirect('authz:login')


                auth.login(request, user)
                return redirect('dashboard:dash')
            else:
                messages.info(request, 'Invalid credentials')
                return redirect('authz:login')
        else:
            messages.info(request, 'Invalid credentials')
            return redirect('authz:login')
    return render(request, "authz/login.html")


# ============================================
# ============================================


def logout(request):
    auth.logout(request)
    return redirect('/')


# =============================================
# =============================================


def signup(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        country = request.POST['country']
        phone_num= request.POST['phone_mobile_prefix'] + request.POST['phone_mobile']
      
        date_of_birth = request.POST['dob3'] + "/" + request.POST['dob2'] + "/" + request.POST['dob1']
   
        account_type = request.POST['account_type']
        currency_base = request.POST['currency_base']
        try:
            bonus_scheme = request.POST['bonus_scheme']
        except:
            bonus_scheme = "Not Applicable"
        leverage = request.POST['leverage']
        password = request.POST['password']
        pass2 = request.POST['confirm_password']
        email = email.lower()
        if password == pass2:
            if User.objects.filter(email=email).exists():
                messages.info(request, "Email already exist")
                return redirect('authz:signup')
            else:

                user = User.objects._create_user(email, password, first_name, last_name, phone_num, date_of_birth, country)
                user.save()
                send_activation_email(user,request)   
        else:
            messages.info(request, "Password didnt match")
            return redirect('authz:signup')
           
        account_number= 0
        while (account_number == 0):
            ref2 = generateAccountNumber()
            object_with_similar_ref = Account.objects.filter(account_number=ref2)
            if not object_with_similar_ref:
                account_number = ref2
        acc = Account.objects.create(user=user,account_number=account_number,account_type=account_type,currency_base=currency_base,
        bonus_category=bonus_scheme,leverage=leverage)
        acc.save()

        messages.info(request, "Account created, check your email for activation link")
        return redirect('authz:login')
        
    return render(request, "authz/signup.html")

def activate_user(request,uidb64,token):
    
    try:
        uid= force_str(urlsafe_base64_decode(uidb64))

        user=User.objects.get(pk=uid)

    except Exception as e:
        user= None

    if user and generate_token.check_token(user,token):
        user.is_email_verified= True
        user.save()

        messages.info(request, "email verified")
        return redirect('authz:login')

    return render(request, 'authz/activation_fail.html', {'user':user})


def resend_email(request):
    if request.method == 'POST':
        email = request.POST['email']
        user= User.objects.get(email=email)
        send_activation_email(user,request)
        messages.info(request, "email resent")
        return redirect('authz:login')

authz/templates/authz/activate.html
{% autoescape off %}

Hi {{user.first_name}}
Please use the link below to verify your account.

http://{{domain}}{% url 'authz:activate' uidb64=uid token=token %}

Ignore if you didn't make the request.


{% endautoescape %}

authz/templates/authz/activation_fail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
			<meta name="language" content="en" />
	<meta http-equiv="imagetoolbar" content="no" />
	
	<link rel="manifest" href="{% static 'lte/js/manifest.json' %}">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800">
	<link rel="stylesheet" href="{% static 'lte/css/bootstrap.min.css' %}" />
	<link rel="stylesheet" href="{% static 'lte/css/bootstrap-select.min.css' %}" />
	<link rel="stylesheet" href="{% static 'lte/css/bootstrap-datepicker.min.css' %}" />
	<link rel="stylesheet" href="{% static 'lte/css/lte.min.css' %}" />
	<link rel="stylesheet" href="{% static 'lte/css/flags.css' %}" />
			<link rel="stylesheet" href="{% static 'lte/css/icomoon.css' %}" />
		<link rel="stylesheet" href="{% static 'lte/css/style-providers-list.css' %}" />
	<link rel="stylesheet" href="{% static 'lte/css/common.css' %}" />
		<script type="text/javascript" src="{% static 'lte/js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'lte/js/iframeResizer.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'lte/js/lte.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'lte/js/popper.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'lte/js/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'lte/js/bootstrap-select.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'lte/js/bootstrap-datepicker.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'lte/js/widget-providers-list.js' %}"></script>
								<link type="text/css" rel="stylesheet" href="{% static 'lte/css/page-forgot-password.css' %}" />
							<link rel="icon" type="image/png" href="{% static 'lte/img/favicon.png' %}" />
		  <script>
    function getUrlVars() {
      var vars = [], hash;
      var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
      for(var i = 0; i < hashes.length; i++) {
        hash = hashes[i].split('=');
        vars[hash[0]] = hash[1];
      }

      return vars;
    }

    function setCookie(cname, cvalue, exdays) {
      var d = new Date();
      d.setTime(d.getTime() + (exdays*24*60*60*1000));
      var expires = "expires="+ d.toUTCString();
      document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
    }

    function isEmpty(obj) {
      for(var prop in obj) {
        if(obj.hasOwnProperty(prop)) {
          return false;
        }
      }

      return JSON.stringify(obj) === JSON.stringify(new Object());
    }

    var vars = getUrlVars();
    var cookieValues = new Object();

    var non_utm_params = ['gclid', 'fbclid', 'msclkid'];
    for(var entry in vars) {
      if(entry.startsWith("utm_") || non_utm_params.includes(entry)){
        cookieValues[entry] = vars[entry];
      }
    }

    if (!isEmpty(cookieValues)) {
      setCookie('UrlOriginalQueryParameters', JSON.stringify(cookieValues), 30);
    }


  </script>

	
	

	
    <!-- Google Tag Manager --> <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-M4FCQ59');</script> <!-- End Google Tag Manager -->


	<!-- PushWoosh goes here -->
	<script type="text/javascript" src="//cdn.pushwoosh.com/webpush/v3/pushwoosh-web-notifications.js" async></script>
	<script type="text/javascript" src="{% static 'lte/js/pushwoosh-service-worker-init.js' %}"></script>
<style>
		  .logo-image{
width:100px;
height: 30px;
border-radius: 50%;
overflow: hidden;
margin-top: -6px;

}
	</style>
</head>    <body class="sidebar-mini client-portal lang-en cont-ea">
    
<!-- Google Tag Manager (noscript) --> <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M4FCQ59" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript> <!-- End Google Tag Manager (noscript) -->


        <div class="wrapper">
            <nav class="main-header navbar navbar-expand   ">
    
        <ul class="navbar-nav left">
                    <a href="{% url 'alph:index' %}" class="brand-link d-block">
                <div class="logo-image">
                      <img src="{% static 'Home page/wp-content/uploads/2021/10/Alphforex logo.png'%}"  class="img-fluid">
                </div>
            </a>
            </ul>
        <ul class=" navbar-nav right ml-auto">
                                                <li class="nav-item">
                    <a id="btn-navbar-register" href="{% url 'authz:signup' %}" target="_blank" class="nav-link btn btn-green">Register</a>
                </li>
                        
	<li class="nav-item dropdown language">
																			<a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
					en
					<span class="nav-icon icon icon-dropdown-close right"></span>
			    </a>
																																																				<div class="dropdown-menu dropdown-menu-right">
							
									<a href="#/ar/forgot" class="dropdown-item">
						<span class="flag flag-ar"></span>
						العربية
					</a>
											
									<a href="#/de/forgot" class="dropdown-item">
						<span class="flag flag-de"></span>
						Deutsch
					</a>
											
									<a href="#/en/forgot" class="dropdown-item">
						<span class="flag flag-en"></span>
						English
					</a>
											
									<a href="#/es/forgot" class="dropdown-item">
						<span class="flag flag-es"></span>
						Español
					</a>
											
									<a href="#/fr/forgot" class="dropdown-item">
						<span class="flag flag-fr"></span>
						Français
					</a>
											
									<a href="#/nl/forgot" class="dropdown-item">
						<span class="flag flag-nl"></span>
						Dutch
					</a>
											
									<a href="#/id/forgot" class="dropdown-item">
						<span class="flag flag-id"></span>
						Bahasa Indonesia
					</a>
											
									<a href="#/it/forgot" class="dropdown-item">
						<span class="flag flag-it"></span>
						Italiano
					</a>
											
									<a href="#/ms/forgot" class="dropdown-item">
						<span class="flag flag-ms"></span>
						Bahasa Melayu
					</a>
											
									<a href="#/pt/forgot" class="dropdown-item">
						<span class="flag flag-pt"></span>
						Português
					</a>
											
									<a href="#/vi/forgot" class="dropdown-item">
						<span class="flag flag-vi"></span>
						Tiếng Việt
					</a>
											
									<a href="#/zh/forgot" class="dropdown-item">
						<span class="flag flag-zh"></span>
						中文
					</a>
									</div>
	</li>

            </ul>
</nav>            
            <div class="main-content content-wrapper">
                
	<div class="row  lte-public">
		<div class="col-sm-12 col-md-11 col-lg-8 main-content-container container-center">
			<section class="content">
				<div class="row justify-content-md-center">
					<div class="col-sm-12  col-md-6 col-lg-6 ">
												<div class="card ">
													<h3 class="center"><b>Token not valid!</b></h3>
                                                
									<p class="center">Its either you've used the token and your account has been verified or it has expired</p>
							<form method="post" autocomplete="on" action="{% url 'authz:resend_email' %}" class="forgot-form">
								<div class="card-body">
	{% csrf_token %}
    	{% csrf_token %}
                <label for="email">Enter your Email:</label><br>
                <input type="email" name="email"><br>
                <input type="submit" value="Resend verification Email">
										</div>
										<!-- <div class="form-group">
											
																							<label for="password">Enter code</label>
																						<div class="row ">
												<div class=" col-sm-3  left">
													<img src="#/human-test/?source=live&amp;random=23674" class="captcha">
													<input type="hidden" value="" name="ironcookie" id="ironcookie">
												</div>
                                                <form method="post" autocomplete="on" action="{% url 'authz:resend_email' %}">
				{% csrf_token %}
                <label for="email">Enter your Email:</label><br>
                <input type="email" name="email"><br>
                <input type="submit" value="Resend verification Email">
            
            </form>
												<div class=" col-sm-9 right ">
													<input type="text" class="form-control "
													   value="" id="captcha" name="captcha" required placeholder="">
													
												</div>
											</div>
										</div> -->
									<!-- </div>
								</div> -->
								<!-- <div class="card-footer">
																				<div class="form-group center">
												<button id="btn-forgot-password" type="submit" class="btn  btn-default btn-blue">Submit</button>
											</div>
																			</div> -->
							</form>
						</div>
					</div>
				</div>
			</section>
		</div>
	</div>

            </div>
            
<footer class="main-footer  ">
    <div class="row">
                    <div class="col-sm-12 col-md-11 main-footer-container col-lg-8">
                <div class="row">
                                                                <div class="col-sm-12 col-md-3 col-md-3 ">
                            <p>&copy; 2022 AlphaForex.<br/>All Rights Reserved.</p>
                                                                                    
                            
                            
                            
                            
                            
                                                    </div>
                                                                <div class="col-sm-12 col-md-9 ">
                                                        <p>AlphaForex, with registered address of F20, 1st Floor, Eden Plaza, Eden Island, Seychelles, is a trade name of Tradeco Limited.</p>
<p>The Group includes Damadah Holding Limited with registration number HE 324249 and registered address at 365, Agiou Andreou, Efstathiou Court, 2nd Floor, Flat 201, 3035 Limassol, Cyprus.</p>
<p>Tradeco limited is authorised and regulated by the Seychelles Financial Services Authority with licence number SD029.</p>
<p><strong>Risk Warning:</strong></p>
<p>Our products are traded on margin and carry a high level of risk and it is possible to lose all your capital. These products may not be suitable for everyone and you should ensure that you understand the risks involved.

</p>
<p>AlphaForex does not offer its services to residents of certain jurisdictions such as USA, Iran, Cuba, Sudan, Syria and North Korea.

</p><ul class="list-inline"><li class="list-inline-item"><img src="{% static 'lte/img/visa.svg' %}" alt="Visa"></li><li class="list-inline-item"><img src="{% static 'lte/img/mastercard.svg' %}" alt="Mastercard"></li></ul>                        </div>
                    </div>
                </div>
            </div>
            </div>
</footer>
    

<script src="https://browser.sentry-cdn.com/5.6.3/bundle.min.js" integrity="sha384-/Cqa/8kaWn7emdqIBLk3AkFMAHBk0LObErtMhO+hr52CntkaurEnihPmqYj3uJho" crossorigin="anonymous">
</script>
<script>
    Sentry.init({
        dsn: 'https://e2e81990b3724730ab503e62b77d44f1@sentry.io/134335',
        release: ''
    });
</script>

<script type="text/javascript">
    
    
    
    var Site = jQuery.extend( { } , {
        language: "en",
        ssl: true,
        context: "ea",
        domain: "#",
        brand: "AlphaForex",
        soliticsPopupToken: "JJhD3J2KCVkNMkB3uesXUxu2",
        soliticsBrand: "BqTgCkN4KzyPu2dqcVnqwKWE",
        portalId: "",
        guid: "",
    } );
</script>
<script type="text/javascript" src="{% static 'lte/js/jquery-migrate.min.js' %}"></script>
<script type="text/javascript" src="{% static 'lte/js/jquery-form.js' %}"></script>
<script type="text/javascript" src="{% static 'lte/js/jquery-widget.js' %}"></script>
<script type="text/javascript" src="{% static 'lte/js/jquery-cookie.js' %}"></script>
<script type="text/javascript" src="{% static 'lte/js/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'lte/js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'lte/js/sso.js' %}"></script>
<script type="text/javascript" src="{% static 'lte/js/widget-login.js' %}"></script>
<script type="text/javascript" src="{% static 'lte/js/deposit-list.js' %}"></script>
<script type="text/javascript" src="{% static 'lte/js/jcarousel/jquery.jcarousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'lte/js/referrer.js' %}"></script>
                <script type="text/javascript" src="{% static 'lte/js/page-forgot.js' %}"></script>
            </div>
    </body>
</html>